"""payment refactor

Revision ID: 00b8f6e80d1d
Revises: 7ac90ab08ca9
Create Date: 2025-07-04 14:30:48.929531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b8f6e80d1d'
down_revision = '7ac90ab08ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
