"""fix subscription structure

Revision ID: 92c4c481d8d2
Revises: da62cd960ab9
Create Date: 2025-07-04 09:11:15.182693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c4c481d8d2'
down_revision = 'da62cd960ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('renewal_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('renewal_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
